---
- name: Backup Cisco IOS Devices
  gather_facts: no
  hosts: "{{ variable_host }}"
  connection: network_cli

  tasks:
    - name: Backup running-config
      ios_config:
        backup: yes
...
# Command to run:
# ansible-playbook -i ./inventory ios_config_backup.yaml --extra-vars "variable_host=routers"
