---
- name: Running show commands on Cisco IOS
  hosts: "{{ variable_host }}"
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Run multiple commands on Cisco IOS nodes
      ios_command:
        commands:
          - show run
      register: print_output
    - debug: var=print_output.stdout_lines

...