---
- name: Configuring Cisco IOS Hostnames
  hosts: "{{ variable_host }}"
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure hostname
      ios_config:
         lines: hostname {{ inventory_hostname }}
    - name: Printing at the console
      debug: var=output

...
# Command to run:
# ansible-playbook -i inventory set_hostnames.yaml --extra-vars "variable_host=routers" -vvv

