acls:
- acls:
  - aces:
    - grant: deny
      sequence: 10
      source:
        host: 100.100.100.100
    acl_type: standard
    name: '11'
  - aces:
    - destination:
        any: true
        port_protocol:
          eq: domain
      grant: deny
      protocol: udp
      sequence: 100
      source:
        any: true
    - destination:
        any: true
        port_protocol:
          eq: domain
      grant: deny
      protocol: tcp
      sequence: 101
      source:
        any: true
    - destination:
        any: true
      grant: deny
      protocol: udp
      sequence: 102
      source:
        any: true
        port_protocol:
          eq: bootps
    - destination:
        any: true
        port_protocol:
          eq: bootpc
      grant: deny
      protocol: udp
      sequence: 103
      source:
        any: true
    - destination:
        any: true
      grant: deny
      protocol: udp
      sequence: 104
      source:
        any: true
        port_protocol:
          eq: bootpc
    - destination:
        any: true
        port_protocol:
          eq: www
      grant: permit
      protocol: tcp
      sequence: 105
      source:
        any: true
    acl_type: extended
    name: CISCO-CWA-URL-REDIRECT-ACL
  - aces:
    - destination:
        any: true
        port_protocol:
          eq: domain
      grant: permit
      protocol: udp
      sequence: 10
      source:
        any: true
    - destination:
        any: true
        port_protocol:
          eq: domain
      grant: permit
      protocol: tcp
      sequence: 20
      source:
        any: true
    - destination:
        any: true
      grant: permit
      protocol: udp
      sequence: 30
      source:
        any: true
        port_protocol:
          eq: bootps
    - destination:
        any: true
        port_protocol:
          eq: bootpc
      grant: permit
      protocol: udp
      sequence: 40
      source:
        any: true
    - destination:
        any: true
      grant: permit
      protocol: udp
      sequence: 50
      source:
        any: true
        port_protocol:
          eq: bootpc
    - destination:
        any: true
      grant: deny
      protocol: ip
      sequence: 60
      source:
        any: true
    acl_type: extended
    name: preauth_ipv4_acl (per-user)
  afi: ipv4
- acls:
  - aces:
    - destination:
        any: true
        port_protocol:
          eq: domain
      grant: permit
      protocol: udp
      sequence: 10
      source:
        any: true
    - destination:
        any: true
        port_protocol:
          eq: domain
      grant: permit
      protocol: tcp
      sequence: 20
      source:
        any: true
    - destination:
        any: true
      grant: permit
      protocol: icmp
      source:
        any: true
    - destination:
        any: true
      grant: permit
      protocol: icmp
      protocol_options:
        icmp:
          router_solicitation: true
      sequence: 50
      source:
        any: true
    - destination:
        any: true
      grant: permit
      protocol: icmp
      protocol_options:
        icmp:
          router_advertisement: true
      sequence: 60
      source:
        any: true
    - destination:
        any: true
      grant: permit
      protocol: icmp
      protocol_options:
        icmp:
          redirect: true
      sequence: 70
      source:
        any: true
    - destination:
        any: true
        port_protocol:
          eq: '546'
      grant: permit
      protocol: udp
      sequence: 80
      source:
        any: true
        port_protocol:
          eq: '547'
    - destination:
        any: true
        port_protocol:
          eq: '547'
      grant: permit
      protocol: udp
      sequence: 90
      source:
        any: true
        port_protocol:
          eq: '546'
    - destination:
        any: true
      grant: deny
      protocol: ipv6
      sequence: 100
      source:
        any: true
    name: preauth_ipv6_acl (per-user)
  afi: ipv6
